### ISSUE TITLE
Почему все файлы нет?

### ISSUE THREAD

**Issue by Specialist001** [nurbeknurjanov/yii2ecommerce#1]
Привет Нурбек ака. Почему все файлы нету? И без документации

**Comment by nurbeknurjanov** [comment]
> Привет Нурбек ака. Почему все файлы нету? И без документации

Привет. Пока это не опен сорс. Только для код ревью выложил часть кода.

**Comment by Specialist001** [comment]
Тогда ждем опен сорс вариант
