### ISSUE TITLE
Error on yii fixture

### ISSUE THREAD

**Issue by mmerola84** [nurbeknurjanov/yii2ecommerce#3]
Hi, when I call yii fixture here the error:

Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list'
The SQL being executed was: INSERT INTO `user` (`id`, `username`, `auth_key`, `password_hash`, `name`, `email`, `status`, `created_at`, `updated_at`, `language`, `time_zone`, `referrer_id`, `from`, `description`, `subscribe`) VALUES (1, 'admin', '_gOPydMje6EV9PR3IqAk5bK8h9BM6OLn', '$2y$13$g0Xj.0poxUBuFQzLjWKrFuHEgxmxPqMFbP.6BrOt5rJ3VLWKjySc2', 'Nurbek Nurjanov', 'nurbek.nurjanov@mail.ru', 10, 1618823269, 1618823269, 'en-US', 'Asia/Almaty', '0', '', '<p>Yii developer</p>', 1)'

Db are old?

**Comment by nurbeknurjanov** [comment]
Next week I gonna update repository. And yes, I will upload new db.

**Comment by nurbeknurjanov** [comment]
I have restored repo, u can check
